config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :questions do
    collection do
      get :unsolved
      get :solved
    end
    resources :answers,only: [:create]
  end
  root to: 'questions#index'
  
  namespace :admin do
    root to: 'questions#index'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :users
    resources :questions, only: [:index, :destroy]
  end
  
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    belongs_to :user

    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    validates :title, presence: true, length: { maximum:30 }
    validates :description, presence: true
    
    belongs_to :user

    has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    has_many :questions, dependent: :destroy
    has_many :answers, dependent: :destroy
  
    # mount_uploader :avatar, AvatarUploader
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
   before_action :require_admin
    
   def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(8)
   end

   def destroy
    @question = Question.find(params[:id])
    @question.destroy!
    redirect_to admin_questions_url, notice: "質問 「#{@question.title}」を削除しました。"
  end





    private

    def require_admin
        if current_user.nil? || !current_user.admin?
          redirect_to root_path, notice: '管理者ではありません'
        end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  before_action :set_admin_user, {only: [:show,:update, :destroy]}

 def index
   @users = User.all
 end

 def show
 end
 
 def new
   @user = User.new
 end

 def edit
   @user = User.find(params[:id])
 end

 def create
   @user = User.new(user_params)

   if @user.save 
     redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
   else
     render :new
   end
 end

 def update
   if @user.update(user_params)
     redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました"
   else
     render :new
   end
 end
 
 def destroy
   @user.destroy
   redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました"
 end
 

 private 

 def user_params
   params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
 end

 def require_admin
  if current_user.nil? || !current_user.admin?
    redirect_to root_path, notice: '管理者ではありません'
  end
 end

 def set_admin_user
  @user = User.find(params[:id])
end
 
 
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :authenticate_user
    
    
    
    def create
      @answer = Answer.new(answer_params)
      @answer.user_id = current_user.id
      @answer.question_id  = params[:question_id]
      if @answer.save!
        AnswerMailer.with(answer: @answer).creation_answer.deliver_now

        answers = Answer.where(question_id: @answer.question_id)
        user_ids = answers.pluck(:user_id)
        users = User.where(id: user_ids)
        users.each do |user|
          next if user == current_user
          AnswerMailer.with(user: user, answer: @answer).creation_other_answers.deliver_now
        end
        redirect_to("/questions/#{params[:question_id]}")         
      else
        render :new
      end
    end

    
      
    private
      def answer_params
        params.require(:answer).permit(:description).merge(question_id: params[:question_id] )
      end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_user


    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    

    def authenticate_user 
        if @current_user == nil
          redirect_to login_path, notice: "ログインが必要です。"
        end
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
 
  before_action :authenticate_user, {only:[:new, :create, :edit, :update, :destroy]}
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}
  before_action :set_question, {only:[:show, :edit, :update, :destroy]}


  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(8)
  end

  def show
    @answers = @question.answers
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save!
      User.all.each do |user|
       next if user == current_user
       QuestionMailer.with(user: user, question: @question).creation_email.deliver_now
      end
       redirect_to questions_url, notice: "質問 「#{@question.title}」を投稿しました。" 
    else
      render :new
    end
  end

  def update
    @question.update!(question_params)
    redirect_to questions_url, notice: "質問 「#{@question.title}」を更新しました。"
  end
  
  def destroy
    @question.destroy!
    redirect_to questions_url, notice: "質問 「#{@question.title}」を削除しました。"
  end

  def solved
    @q = Question.where(solved: true).ransack(params[:q])
    @questions = @q.result(distinct: 0).page(params[:page]).per(10)
    render :action => 'index'
  end
  
  def unsolved
    @q = Question.where(solved: false).ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(10)
    render :action => 'index'
  end
  
  private
  def question_params
    # byebug
    params.require(:question).permit(:title,:description,:solved)
  end

  def ensure_correct_user
    @question = Question.find_by(id: params[:id])
    if @question.user_id != current_user.id
      redirect_to root_url, notice: "管理者権限がありません"
    end
  end
  
  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'ログインしました'
    else
      render :new
    end 
  end

  def destroy
     reset_session
     redirect_to root_url, notice: 'ログアウトしました'
  end
  

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user,{only:[:index,:show,:edit,:update]}
    before_action :ensure_correct_user, {only: [:edit, :update]}
    before_action :set_user, {only: [:show, :edit, :update]}

 def index
  @q = User.ransack(params[:q])
  @users = @q.result(distinct: true).page(params[:page]).per(10)
 end

 def show
 end
 
 def new
   @user = User.new
 end

 def edit
 end

 def create
   @user = User.new(user_params)

   if @user.save 
     session[:user_id] = @user.id
     redirect_to questions_url, notice: "ユーザー「#{@user.name}」を登録しました。"
   else
     render :new
   end
 end

 def update
   if @user.update(user_params)
     redirect_to user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました"
   else
     render :new
   end
 end
 
 def destroy
   @user = User.find(params[:id])
   @user.destroy
   redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました"
 end
 

 private 

 def user_params
   params.require(:user).permit(:name, :email, :avatar, :password, :password_confirmation)
 end

 def ensure_correct_user
    if @current_user.id != params[:id].to_i
      redirect_to root_url, notice: "権限がありません"
    end
 end

 def set_user
    @user = User.find(params[:id])
 end

end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/questions/index.html.slim
h1 質問一覧

= search_form_for [:admin,@q], class: 'my-5' do |f| 
  .form-group.row
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control', placeholder: '検索ワード'
    .col-sm-2
      = f.submit class: ' btn btn-outline-primary'


.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = Question.human_attribute_name(:title)
      th = Question.human_attribute_name(:created_at)
  tbody
   - @questions.each do |question|
     tr 
        td = link_to question.title, question
        td = question.created_at
        td 
          = link_to  "削除", [:admin, question], method: :delete, data: {confirm: "質問「#{question.title}」を削除します。よろしいですか？"}, class: 'btn btn-danger' 
.mb-3
  = paginate @questions

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messafes. each do |message|
      li= message

= form_with model: [:admin,@user], local: true do |f|
  .form-group
    = f.label :name,'名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email,'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input' 
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
  = link_to  "一覧", admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to  "新規登録", new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name(:name)
      th = User.human_attribute_name(:email)
      th = User.human_attribute_name(:admin)
      th = User.human_attribute_name(:created_at)
      th = User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td = link_to user.name, [:admin, user]
        td = user.email
        td = user.admin? ? 'あり' : 'なし'
        td = user.created_at
        td = user.updated_at
        td
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
          = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  = link_to  "一覧", admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }  

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-end
  = link_to  "一覧", admin_users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to  "編集", edit_admin_user_path, class: 'btn btn-primary'
= link_to  "削除", [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/answers/_form.html.slim
= form_with model: answer, local: true do |f|
  .form-group
    = f.label :description
    = f.text_area :description, rows:5, class: 'form-control', id: 'answer_description'
  = f.submit nil, class: 'btn btn-primary'

app/views/answers/edit.html.slim
h1 回答編集画面

.nav.justify-content-end
  = link_to '一覧', answers_path, class: 'nav-link'

= render partial: 'form', locals: { answer: @answer }

app/views/answers/index.html.slim
h1 回答一覧

= link_to '新規登録', new_answer_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Answer.human_attribute_name(:title)
      th
  tbody
    - @answers.each do |answer|
      tr
        td= link_to answer.title, answer
        td= answer.created_at
        td
          = link_to '編集', edit_answer_path(answer), class: 'btn btn-primary mr-3'
          = button_to '削除', answer, method: :delete, data: { confirm: "回答を削除してよろしいですか？"}, class: 'btn btn-danger'

app/views/answers/new.html.slim
h1 回答の新規登録

.nav.justify-content-end
  = link_to '一覧', answers_path, class: 'nav-link'

= form_with model: @answer, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'answer_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows:5, class: 'form-control', id: 'answer_description'
  = f.submit nil, class: 'btn btn-primary'

app/views/answers/show.html.slim
h1 回答内容

table.table.table-hover
  tbody
    tr
      th= Answer.human_attribute_name(:id)
      td= @answer.id
    tr
      th= Answer.human_attribute_name(:title)
      td= @answer.title
    tr
      th= Answer.human_attribute_name(:description)
      td= simple_format(h(@answer.description),{}, sanitize:false, wrapper_tag: "div")
    tr
      th= Answer.human_attribute_name(:created_at)
      td= @answer.created_at
    tr
      th= Answer.human_attribute_name(:updated_at)
      td= @answer.updated_at

= link_to '編集', edit_answer_path, class: 'btn btn-primary mr-3'
= button_to '削除', @answer, method: :delete, data: { confirm: "質問を削除してよろしいですか？"}, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | QandA
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navber.navber-expand-md.navber-light.bg-light
      .navber-brand QandA

      ul.navbar-nav.ml-auto
        - if @current_user
          - if @current_user.admin?
            li.nav-item= link_to  "ユーザー一覧", admin_users_path, class: 'nav-link'
            li.nav-item= link_to  "質問一覧", admin_questions_path, class: 'nav-link'
            li.nav-item= link_to  "管理者作成", new_admin_user_path, class: 'nav-link'
            li.nav-item= link_to  "ログアウト", logout_path, method: :delete, class: 'nav-link'
          - else
            li.nav-item= link_to  "質問一覧", root_path, class: 'nav-link'
            li.nav-item= link_to  "ユーザー一覧", users_path, class: 'nav-link'
            li.nav-item= link_to  "/users/#{@current_user.id}" 
                        = image_tag  "icons8-customer-100", :class => 'rounded-circle', :size =>'30x30' 
            li.nav-item= link_to  "ログアウト", logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to  "新規登録", new_user_path, class: 'nav-link'
          li.nav-item= link_to  "質問一覧", root_path, class: 'nav-link'
          li.nav-item= link_to  "ログイン", login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield

app/views/questions/_form.html.slim
- if question.errors.present?
  ul#error_explanation
    - question.errors.full_messages.each do |message|
      li = message


= form_with model: question, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'question_title' 
  .form-group
    = f.label :description
    = f.text_area :description,rows: 5, class: 'form-control', id: 'question_description'
  = f.submit nil, class: 'btn btn-primary' 

app/views/questions/edit.html.slim
h1 質問の編集

- if @question.errors.present?
  ul#error_explanation
    - question.errors.full_messages.each do |message|
      li= message

.nav.justify-content-end
  = link_to  "一覧", question_path,class: 'nav-link'


= form_with model: @question, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'question_title' 
  .form-group
    = f.label :description
    = f.text_area :description,rows: 5, class: 'form-control', id: 'question_description'
  = f.submit nil, class: 'btn btn-primary' 
  
.nav.justify-content-end
  = link_to  "未解決", question_path(@question.id, question: {solved: false }),method: :put
  = link_to  "解決済み", question_path(@question.id, question: {solved: true }),method: :put

app/views/questions/index.html.slim
h1 質問一覧

= link_to  "質問の投稿", new_question_path, class: 'btn btn-primary'  

= link_to 'すべて', questions_path, class: 'btn btn-outline-primary btn-sm ml-2'
= link_to '未解決', unsolved_questions_path, class: 'btn btn-outline-primary btn-sm ml-1'
= link_to '解決済み', solved_questions_path, class: 'btn btn-outline-primary btn-sm ml-1'


= search_form_for @q, class: 'my-5' do |f| 
  .form-group.row
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control', placeholder: '検索ワード'
    .col-sm-2
      = f.submit class: ' btn btn-outline-primary'


.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = Question.human_attribute_name(:title)
      th = Question.human_attribute_name(:created_at)
  tbody
   - @questions.each do |question|
     tr 
        td = link_to question.title, question
        td = question.created_at
        td 
          = link_to  "編集", edit_question_path(question), class: 'btn btn-primary mr-3' 
          = link_to  "削除", question, method: :delete, data: {confirm: "質問「#{question.title}」を削除します。よろしいですか？"}, class: 'btn btn-danger' 
.mb-3
  = paginate @questions

app/views/questions/new.html.slim
h1 質問の新規登録

/ - if @question.errors.present?
/   ul#error_explanation
/     - question.errors.full_messages.each do |message|
/       li= message
      
.nav.justify-content-end 
  = link_to  "一覧", questions_path, class: 'nav-link'

= form_with model: @question, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'question_title'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'question_description'
  = f.submit nil, class: 'btn btn-primary'

app/views/questions/show.html.slim
h1 質問の詳細

.nav.justify-content-end
  - if @current_user.present? && @question.user_id == @current_user.id
    = link_to '編集', edit_question_path, class: 'btn btn-primary mr-1 float-right'
    = link_to '削除', @question, method: :delete, data: { confirm: "質問「#{@question.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger float-right'
  
  
table.table.table-hover
  tbody
    tr
      th = Question.human_attribute_name(:title)
      td = @question.title
    tr
      th = Question.human_attribute_name(:description)
      td = simple_format(h(@question.description), {}, sanitize: false, wrapper_tag: "div" )

= form_with model:[@question, @answer], local: true do |f|
  .form-group
    = f.label :description
    = f.text_area :description, rows:5, class: 'form-control', id: 'answer_description'
  = f.submit '回答する' , class: 'btn btn-primary'

.mb-3
table.table.table-hover
  tbody
    - @question.answers.each do |answer|
      tr
        td= answer.description
        

app/views/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: user, local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
  = f.label :avatar, '画像'
  = f.file_field :avatar, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
  = link_to '一覧', users_path, class: 'nav-link'
  
= render partial: 'form', locals: { user: @user }

app/views/users/index.html.slim
= search_form_for @q, class: 'my-5' do |f| 
  .form-group.row
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control', placeholder: '検索ワード'
    .col-sm-2
      = f.submit class: ' btn btn-outline-primary'

.mb-3
table.table.table-hover
  thead.thead-default
  tbody
    - @users.each do |user|
      tr
        td= link_to user
          - if user.avatar?
            = image_tag user.avatar.url, :class => 'rounded-circle', :size =>'32x32' 
          - else
            = image_tag 'icons8-customer-100', :class => 'rounded-circle', :size =>'32x32'
        td= link_to user.name, user
        
        
.mb-3
  = paginate @users

app/views/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  = link_to '一覧', users_path, class: 'nav-link'
  
= render partial: 'form', locals: { user: @user }

app/views/users/show.html.slim
h1 ユーザー詳細

- if @user.id == @current_user.id
  = link_to '編集', edit_user_path, class: 'btn btn-primary float-right'
/ ユーザーを編集できるのは自分だけ
  
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:avatar)
      td
        - if @user.avatar?
          = image_tag @user.avatar.url, :class => 'rounded-circle', :size =>'32x32'
        - else
          = image_tag 'icons8-customer-100', :class => 'rounded-circle', :size =>'32x32'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at